using EventHub.Domain.Entities;
using EventHub.Domain.ValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EventHub.Infrastructure.Persistence.Configurations;

public class EventConfiguration : IEntityTypeConfiguration<Event>
{
    public void Configure(EntityTypeBuilder<Event> builder)
    {
        // Table name in database
        builder.ToTable("Events");

        // Id is primary key
        builder.HasKey(e => e.Id);

        // Id is auto-generated by database (IDENTITY column in SQL)
        builder.Property(e => e.Id)
            .ValueGeneratedOnAdd();

        // Title: Required, max length 200 characters
        builder.Property(e => e.Title)
            .IsRequired()
            .HasMaxLength(200);

        // Description: Required, max length 2000 characters
        builder.Property(e => e.Description)
            .IsRequired()
            .HasMaxLength(2000);

        // Source: Required (where we scraped from), max length 100
        builder.Property(e => e.Source)
            .IsRequired()
            .HasMaxLength(100);

        // SourceUrl: Optional (nullable), max length 500
        builder.Property(e => e.SourceUrl)
            .HasMaxLength(500);

        // Category: Stored as integer in database
        // EF Core automatically converts enum ↔ int
        builder.Property(e => e.Category)
            .IsRequired()
            .HasConversion<int>(); // Explicit conversion for clarity

        // Status: Stored as integer in database
        builder.Property(e => e.Status)
            .IsRequired()
            .HasConversion<int>();

        // StartDate: Required, stored as DateTime
        builder.Property(e => e.StartDate)
            .IsRequired();

        // EndDate: Required, stored as DateTime
        builder.Property(e => e.EndDate)
            .IsRequired();

        // CreatedAt: Required, defaults to current UTC time
        builder.Property(e => e.CreatedAt)
            .IsRequired();

        // UpdatedAt: Required, auto-updated on changes
        builder.Property(e => e.UpdatedAt)
            .IsRequired();

        builder.OwnsOne(e => e.Location, location =>
        {
            // Location properties become columns in Events table

            location.Property(l => l.Address)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("Address"); // Simpler column name

            location.Property(l => l.City)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("City");

            location.Property(l => l.Country)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Country");

            // Coordinates are optional (nullable)
            location.Property(l => l.Latitude)
                .HasColumnName("Latitude");

            location.Property(l => l.Longitude)
                .HasColumnName("Longitude");
        });


        // Index on Status - frequently queried (WHERE Status = Active)
        builder.HasIndex(e => e.Status)
            .HasDatabaseName("IX_Events_Status");

        // Index on Category - used in filtering (WHERE Category = Technology)
        builder.HasIndex(e => e.Category)
            .HasDatabaseName("IX_Events_Category");

        // Index on StartDate - used in date range queries and sorting
        builder.HasIndex(e => e.StartDate)
            .HasDatabaseName("IX_Events_StartDate");

        // Composite index on Status + StartDate
        // Optimizes: WHERE Status = Active AND StartDate > @date
        builder.HasIndex(e => new { e.Status, e.StartDate })
            .HasDatabaseName("IX_Events_Status_StartDate");
    }
}